"Nuget\nuget.exe" push "GQ.Charts\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Compiler\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Core\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Data\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.GoogleApi\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Html\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Html.Rest\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Log\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Mail\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.NoSql\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.NoSql.Mongo\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Notification\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Security\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Security.JWT\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Security.MCV\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Socket\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Sql\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Sql.MySQL\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Sql.SQLServer\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
"Nuget\nuget.exe" push "GQ.Template\bin\Release\*.nupkg" g3m1nusQh0m.! -Source http://gq-test2.cloudapp.net/nuget/api/v2/package
